#include "trie_func.h"

//void insert(char* string,struct node * root, char* val);

void insert_data(struct node * root) {
    insert("ACW", root, "Advanced Components");
    insert("AI", root, "Archäometrie / Industriearchäologie");
    insert("AST", root, "Aufbaustudiengang Silikattechnik");
    insert("AUV", root, "Aufbaustudiengang Umweltverfahrenstechnik");
    insert("AWi", root, "Aufbaustudiengang Wirtschaftswissenschaften");
    insert("BAF", root, "Bachelor Additive Fertigung");
    insert("BAI", root, "Bachelor Angewandte Informatik");
    insert("BBL", root, "Bachelor Business and Law");
    insert("BBWL", root, "Bachelor Betriebswirtschaftslehre");
    insert("BCH", root, "Bachelor Chemie");
    insert("BEC", root, "Bachelor Engineering & Computing");
    insert("BENG", root, "Bachelor Engineering");
    insert("BESM", root, "Bachelor Elektronik- und Sensormaterialien");
    insert("BET", root, "Bachelor Energietechnik");
    insert("BFWK", root, "Bachelor Fahrzeugbau, Werkstoffe und Komponenten");
    insert("BGeo", root, "Bachelor Geologie Paläontologie");
    insert("BGi", root, "Bachelor Gießereitechnik");
    insert("BGIP", root, "Bachelor Geoinformatik und Geophysik");
    insert("BGM", root, "Bachelor Geologie und Mineralogie");
    insert("Bgy", root, "Bachelor Geophysik");
    insert("BGÖK", root, "Bachelor Geoökologie");
    insert("BIE", root, "Bachelor Internet der Energie");
    insert("BINA", root, "Bachelor Industriearchäologie");
    insert("BMB", root, "Bachelor Maschinenbau");
    insert("BNAT", root, "Bachelor Angewandte Naturwissenschaft");
    insert("BNC", root, "Bachelor Networkcomputing");
    insert("BTM", root, "Bachelor Technologiemanagement");
    insert("BUWE", root, "Bachelor Umwelt-Engineering");
    insert("BVT", root, "Bachelor Verfahrenstechnik");
    insert("BWIW", root, "Bachelor Wirtschaftsingenieurwesen");
    insert("BWL", root, "Betriebswirtschaftslehre");
    insert("BWM", root, "Bachelor Wirtschaftsmathematik");
    insert("Ch", root, "Chemie");
    insert("CMS", root, "Computational Material Science");
    insert("CSE", root, "Computational Engineering & Computing"); 
    insert("EC", root, "Engeneering & Computing"); //Der Schreibfehler bei Engineering wurde so aus dem Abkürzungsverzeichnis vom Vorlesungsverzeichnis übernommen ;)
    insert("FWK", root, "Fahrzeugbau, Werkstoffe und Komponenten");
    insert("Geo", root, "Geologie");
    insert("GIN", root, "Geoinformatik");
    insert("GTB", root, "Geotechnik und Bergbau");
    insert("Gy", root, "Geophysik");
    insert("Gök", root, "Geoökologie");
    insert("KGB", root, "Keramik-, Glas- und Baustofftechnik");
    insert("M4MB", root, "4-semestriger Master Maschinenbau");
    insert("M4UWE", root, "4-semestriger Master Umwelt-Engineering");
    insert("Ma", root, "Marktscheideweisen und Geodäsie");
    insert("MAI", root, "Master Angewandte Informatik");
    insert("MAMA", root, "Master Advanced Materials Analysis");
    insert("MAMR", root, "International Master of Science in Advanced Mineral Resources Development");
    insert("MB", root, "Maschinenbau");
    insert("MBACS", root, "Master Business Analytics");
    insert("MCH", root, "Master Chemie");
    insert("MEC", root, "Master Engineering & Computing");
    insert("MERW", root, "Master Energie- und Ressourcenwirtschaft");
    insert("MESM", root, "Master Elektronik- und Sensormaterialien");
    insert("MET", root, "Master Energietechnik");
    insert("MFWK", root, "Master Fahrzeugbau, Werkstoffe und Komponenten");
    insert("MGEX", root, "Master Geoscience");
    insert("MGi", root, "Master Gießereitechnik");
    insert("MGIN", root, "Master Geoinformatik");
    insert("MGMRM", root, "Master Geomatics for Mineral Resource Management");
    insert("MGPHY", root, "Master Geophysik");
    insert("MGWM", root, "Master Groundwater Management");
    insert("MGÖK", root, "Master Geoökologie");
    insert("MIK", root, "Master Industriearchäologie/Industriekultur");
    insert("Min", root, "Mineralogie");
    insert("MINA", root, "Master Industrieärchäologie");
    insert("MMB", root, "Master Maschinenbau");
    insert("Mm", root, "Master Angewandte Mathematik");
    insert("MKGB", root, "Master Keramik-,Glas- und Baustofftechnik");
    insert("MMT", root, "Master Metallic Materials Technology");
    insert("MNAT", root, "Master Angewandte Naturwissenschaft");
    insert("MNC", root, "Masterstudiengang Network Computing");
    insert("MNT", root, "Master Nanotechnologie");
    insert("MoRe", root, "Master Sustainable Mining and Remediation");
    insert("MPE", root, "Master Mechanical and Process Engineering");
    insert("MPV", root, "Master Photovoltaik und Halbleitertechnik");
    insert("MTM", root, "Master Technologiemanagement");
    insert("MTR", root, "Master Technikrecht");
    insert("MVT", root, "Master Verfahrenstechnik");
    insert("MWIW", root, "Master Wirtschaftsingenieurwesen");
    insert("MWM", root, "Master Wirtschaftsmathematik");
    insert("Nat", root, "Angewandte Naturwissenschaften");
    insert("NT", root, "Nanotechnologie");
    insert("ROB", root, "Diplomstudiengang Robotik");
    insert("TAIEM", root, "Master Technology and Application of Inorganic Engineering Materials");
    insert("TMA", root, "Technologiemanagement");
    insert("UWE", root, "Umwelt-Engineering");
    insert("VT", root, "Verfahrenstechnik");
    insert("VTC", root, "Diplom Verfahrenstechnik und Chemieingenieurwesen");
    insert("WIW", root, "Diplom Wirtschaftsingenieurwesen");
    insert("WWT", root, "Werkstoffwissenschaft und Werkstofftechnologie");
}